"use client";
import { useEffect, useState } from "react";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState(null); // Initially no theme
  const [isClient, setIsClient] = useState(false); // Track if the client has mounted

  // This effect runs only on the client, after the initial render
  useEffect(() => {
    setIsClient(true); // Set to true once client is mounted

    document.body.setAttribute("cz-shortcut-listen", "true");
    // Only run on the client side
    const savedTheme = localStorage.getItem("theme");
    if (savedTheme) {
      setTheme(savedTheme);
    } else {
      setTheme("light"); // Default theme if none is saved
    }

    // Add a cz-shortcut-listen attribute for some custom handling (if needed)
    document.body.setAttribute("cz-shortcut-listen", "true");
  }, []);

  // Apply theme after client-side mount
  useEffect(() => {
    if (isClient && theme) {
      document.body.classList.remove("light", "dark"); // Remove existing theme classes
      document.body.classList.add(theme); // Add the new theme
      localStorage.setItem("theme", theme); // Save theme preference to localStorage
    }
  }, [isClient, theme]); // Only run when client has mounted and theme is set

  return (
    <SessionProvider>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <html lang="en">
          <body>{children}</body>
        </html>
      </ThemeProvider>
    </SessionProvider>
  );
}
