// import { Inter } from "next/font/google";

// import RoleRedirector from "../lib/RoleRedirect";
import { SessionProvider } from "next-auth/react";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en">
        <body>
          {/* <RoleRedirector /> */}
          <h1>PAge Admin ..</h1>
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
