"use client";
// import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { React, useEffect } from "react"; // Import React
// import RoleRedirector from "../lib/RoleRedirect";
// const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if (typeof window !== "undefined") {
      // Ensure this runs only on the client
      // setLoaded(true); // Uncommented to trigger rendering when loaded
      document.body.setAttribute("cz-shortcut-listen", "true");
    }
  }, []);
  return (
    <SessionProvider>
      <html lang="en">
        <body className="grid h-screen">
          {/* <RoleRedirector /> */}
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
